### ISSUE TITLE
Practica_Diseño de TextBox

### ISSUE THREAD

**Issue by Eva155** [SistemasTecTlaxiaco/diseno-de-control-para-cajas-de-texto-Eva155#2]
[Práctica_Diseño de TexBox personalizado con Visual Studio.pdf](https://github.com/SistemasTecTlaxiaco/diseno-de-control-para-cajas-de-texto-Eva155/files/6332459/Practica_Diseno.de.TexBox.personalizado.con.Visual.Studio.pdf)

**Comment by josealfredo79** [comment]
Bien hecho y revisado
